import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { Urbanist } from 'next/font/google';
import { cn } from '@/lib/utils';

const urbanist = Urbanist({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800'],
  variable: '--font-urbanist',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={cn('antialiased', urbanist.className)}>{children}</body>
    </html>
  );
}
